blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/TimMarsov/MIK32Uploader/blob/main/README.md
    about: Проверьте README и документацию перед созданием issue.
